apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
