apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bnmongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/aggregion/helm-charts-cdp.git
    targetRevision: "master"
    path: bitnami/mongodb
    helm:
      values: |-
        global:
          imageRegistry: registry.aggregion.com
        architecture: replicaset
        replicaCount: 3
        persistence:
          size: 20Gi
        containerSecurityContext:
          enabled: false
        arbiter:
          containerSecurityContext:
            enabled: false
        auth:
          rootPassword: needtochange
          replicaSetKey: rskey
          usernames: []
          # - dmpuser
          # - dsuser
          # - authuser
          # - mdsuser
          passwords: []
          # - needtochange
          # - needtochange
          # - needtochange
          # - needtochange
          databases: []
          # - dmp
          # - ds
          # - auth
          # - mds
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
