apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/aggregion/helm-charts-cdp.git
    targetRevision: "master"
    path: superset
    helm:
      values: |-
        image:
          repository: harbor.aggregion.com/apachesuperset/apache/superset
        initImage:
          repository: harbor.aggregion.com/hub/apache/superset
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
