apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
#    - group: '*'
#      kind: '*'
    - group: ''
      kind: 'Namespace'
    - group: '*'
      kind: 'CustomResourceDefinition'
