apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cdp
  namespace: argocd
  annotations:
    # https://argocd-image-updater.readthedocs.io/en/v0.7.0/configuration/images/
    argocd-image-updater.argoproj.io/image-list: adc=registry.aggregion.com/audience-dataset-consumer,as=registry.aggregion.com/auth-service,dmp=registry.aggregion.com/dmp-backend,gk=registry.aggregion.com/gatekeeper,es=registry.aggregion.com/email-service,ds=registry.aggregion.com/dataservice,oidcp=registry.aggregion.com/oidc-provider,dbmdsc=registry.aggregion.com/db-metadata-sync-consumer,dbmdsync=registry.aggregion.com/db-metadata-sync,ddmec=registry.aggregion.com/ddm-event-consumer,mdsvc=registry.aggregion.com/metadata-service,encsrv=registry.aggregion.com/enclave-server-nodejs,front=registry.aggregion.com/dmp-frontend
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/adc.update-strategy: newest-build
    argocd-image-updater.argoproj.io/adc.allow-tags: regexp:^refs-pull-72-merge-.*$
    argocd-image-updater.argoproj.io/adc.helm.image-name: audienceDatasetConsumer.image.repository
    argocd-image-updater.argoproj.io/adc.helm.image-tag: audienceDatasetConsumer.image.tag
    argocd-image-updater.argoproj.io/as.update-strategy: newest-build
    argocd-image-updater.argoproj.io/as.allow-tags: regexp:^dcp-master-.*$
    argocd-image-updater.argoproj.io/as.helm.image-name: authservice.image.repository
    argocd-image-updater.argoproj.io/as.helm.image-tag: authservice.image.tag
    argocd-image-updater.argoproj.io/dmp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/dmp.allow-tags: regexp:^feature-DMPD-918-story-.*$
    argocd-image-updater.argoproj.io/dmp.helm.image-name: backend.image.repository
    argocd-image-updater.argoproj.io/dmp.helm.image-tag: backend.image.tag
    argocd-image-updater.argoproj.io/ds.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ds.allow-tags: regexp:^dcp-master-.*$
    argocd-image-updater.argoproj.io/ds.helm.image-name: dataservice.imageApi.repository
    argocd-image-updater.argoproj.io/ds.helm.image-tag: dataservice.imageApi.tag
    argocd-image-updater.argoproj.io/gk.update-strategy: newest-build
    argocd-image-updater.argoproj.io/gk.allow-tags: '1.4.2'
    argocd-image-updater.argoproj.io/gk.helm.image-name: gatekeeper.image.repository
    argocd-image-updater.argoproj.io/gk.helm.image-tag: gatekeeper.image.tag
    argocd-image-updater.argoproj.io/oidcp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/oidcp.allow-tags: regexp:^dcp-master-.*$
    argocd-image-updater.argoproj.io/oidcp.helm.image-name: oidcprovider.image.repository
    argocd-image-updater.argoproj.io/oidcp.helm.image-tag: oidcprovider.image.tag
    argocd-image-updater.argoproj.io/dbmdsc.update-strategy: newest-build
    argocd-image-updater.argoproj.io/dbmdsc.allow-tags: regexp:^refs-pull-72-merge-.*$
    argocd-image-updater.argoproj.io/dbmdsc.helm.image-name: dbMetadataSyncConsumer.image.repository
    argocd-image-updater.argoproj.io/dbmdsc.helm.image-tag: dbMetadataSyncConsumer.image.tag
    argocd-image-updater.argoproj.io/dbmdsync.update-strategy: newest-build
    argocd-image-updater.argoproj.io/dbmdsync.allow-tags: regexp:^refs-pull-72-merge-.*$
    argocd-image-updater.argoproj.io/dbmdsync.helm.image-name: dbMetadataSync.image.repository
    argocd-image-updater.argoproj.io/dbmdsync.helm.image-tag: dbMetadataSync.image.tag
    argocd-image-updater.argoproj.io/ddmec.update-strategy: newest-build
    argocd-image-updater.argoproj.io/ddmec.allow-tags: regexp:^refs-pull-72-merge-.*$
    argocd-image-updater.argoproj.io/ddmec.helm.image-name: ddmEventConsumer.image.repository
    argocd-image-updater.argoproj.io/ddmec.helm.image-tag: ddmEventConsumer.image.tag
    argocd-image-updater.argoproj.io/mdsvc.update-strategy: newest-build
    argocd-image-updater.argoproj.io/mdsvc.allow-tags: regexp:^refs-pull-72-merge-.*$
    argocd-image-updater.argoproj.io/mdsvc.helm.image-name: metadataService.image.repository
    argocd-image-updater.argoproj.io/mdsvc.helm.image-tag: metadataService.image.tag
    argocd-image-updater.argoproj.io/es.update-strategy: newest-build
    argocd-image-updater.argoproj.io/es.allow-tags: regexp:^dcp-master-.*$
    argocd-image-updater.argoproj.io/es.helm.image-name: emailservice.image.repository
    argocd-image-updater.argoproj.io/es.helm.image-tag: emailservice.image.tag
    argocd-image-updater.argoproj.io/encsrv.update-strategy: newest-build
    argocd-image-updater.argoproj.io/encsrv.allow-tags: regexp:^main_.*$
    argocd-image-updater.argoproj.io/encsrv.helm.image-name: enclave.imageServer.repository
    argocd-image-updater.argoproj.io/encsrv.helm.image-tag: enclave.imageServer.tag
    argocd-image-updater.argoproj.io/front.update-strategy: newest-build
    argocd-image-updater.argoproj.io/front.allow-tags: regexp:^feature-DCP-2607-story.*$
    argocd-image-updater.argoproj.io/front.helm.image-name: frontend.image.repository
    argocd-image-updater.argoproj.io/front.helm.image-tag: frontend.image.tag
  # if ArgoProject is deleted, delete the child resources (controlled by it project)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: 'https://aggregion.github.io/helm-charts-cdp/charts'
    chart: aggregion-cdp
    targetRevision: '>=0.1.361'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
