apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kc-quark
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: 'https://aggregion.github.io/helm-charts-cdp/charts'
    targetRevision: '>10.0.0'
    chart: keycloak
    helm:
      values: |-
        keycloak:
          enabled: true
        image:
          repository: keycloak
          tag: dcp-master-e32f1b74-10
        auth:
          adminUser: admin
        extraEnvVars:
          - name: KEYCLOAK_PRODUCTION
            value: "true"
          - name: KEYCLOAK_LOG_OUTPUT
            value: "json"
          - name: KEYCLOAK_EXTRA_ARGS
            value: "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true --log-level=INFO,org.keycloak.events:debug"
        postgresql:
          primary:
            persistence:
              size: 1Gi
        service:
         type: NodePort
        proxy: edge
        ingress:
          enabled: true
          hostname: keycloak.localhost
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: self-signed
          tls: true
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
