apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"
  #notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-sync-running.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-deployed.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-health-missing.slack: argocd-deployment
  #notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001670811492"
  #notifications.argoproj.io/subscribe.on-sync-running.telegram: "-1001670811492"
  #notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1001670811492"
  #notifications.argoproj.io/subscribe.on-deployed.telegram: "-1001670811492"
  #notifications.argoproj.io/subscribe.on-health-degraded.telegram: "-1001670811492"
  #notifications.argoproj.io/subscribe.on-health-missing.telegram: "-1001670811492"

resources:
  - project.yml
  #- keycloak.yml
  - externals.yml
  #- atlas.yml
  #- trino.yml
  - cdp.yml
