apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-services
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/aggregion/helm-charts-cdp.git'
    path: charts/pipeline
    targetRevision: 'HEAD'
    helm:
      parameters:
        - name: 'runner.configs.basePipelineOptions.annotations.argocd\.argoproj\.io/sync-wave'
          value: ignore
        - name: 'runner.configs.basePipelineOptions.annotations.argocd\.argoproj\.io/sync-options'
          value: Prune=false
